version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: release/3.x
  ignore:
  - dependency-name: com.diffplug.gradle.spotless
    versions:
    - 5.10.0
    - 5.10.1
    - 5.10.2
    - 5.11.0
    - 5.11.1
    - 5.12.0
    - 5.12.1
    - 5.9.0
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.2-native-mt
  - dependency-name: com.github.ben-manes.versions
    versions:
    - 0.36.0
  - dependency-name: biz.aQute.bnd.builder
    versions:
    - 5.2.0
  - dependency-name: com.google.googlejavaformat:google-java-format
    versions:
    - "1.9"
